local utils = require('tc.telescope.utils')

--- Telescope config
--- Using lua functions
nnoremap('<leader>f', utils.find_files)
nnoremap('<C-f>', utils.live_grep)
nnoremap('<leader>m', utils.grep_string)
nnoremap('<leader>b', utils.buffers)
nnoremap('gr', utils.lsp_references)
nnoremap('<leader>ca', function()
  require('telescope.builtin').lsp_code_actions(require('telescope.themes').get_cursor())
end)
vnoremap('<leader>ca', function()
  require('telescope.builtin').lsp_code_actions(require('telescope.themes').get_cursor())
end)
nnoremap('<leader>gc', utils.git_commits)
nnoremap('<leader>gb', utils.git_bcommits)
nnoremap('<leader>gs', utils.delta_git_status)
nnoremap('<leader>gp', function () require('telescope.builtin').git_bcommits() end)
nnoremap('<leader>sc', function () require('telescope.builtin').spell_suggest() end)
