local utils = require('tc.telescope.utils')

--- Telescope config
--- Using lua functions
nnoremap('<leader>f', utils.find_files)
nnoremap('<C-f>', utils.live_grep)
nnoremap('<leader>m', utils.grep_string)
nnoremap('<leader>b', utils.buffers)
nnoremap('gr', utils.lsp_references)
nnoremap('<leader>ca', function()
  require('telescope.builtin').lsp_code_actions(require('telescope.themes').get_cursor())
end)
vnoremap('<leader>ca', function()
  require('telescope.builtin').lsp_code_actions(require('telescope.themes').get_cursor())
end)
nnoremap('<leader>gc', "<cmd>lua require('telescope.builtin').git_commits()<cr>")
nnoremap('<leader>gb', "<cmd>lua require('telescope.builtin').git_branches()<cr>")
nnoremap('<leader>gs', "<cmd>lua require('telescope.builtin').git_status()<cr>")
nnoremap('<leader>gp', "<cmd>lua require('telescope.builtin').git_bcommits()<cr>")
nnoremap('<leader>p', '<cmd>Telescope projects<cr>')
nnoremap('<leader>sc', "<cmd>lua require('telescope.builtin').spell_suggest()<cr>")
